  openapi_client:
    type: openapi
    kind: client
    options:
      tcp:
        host: localhost
        port: 8080
      specs:
        petstore:
          servers:
            - url: http://localhost:9090
          catalog:
            my_catalog:
              subject: petstore
              version: latest
