  mqtt_kafka_proxy:
    type: mqtt-kafka
    kind: proxy
    options:
      server: mqtt-1.example.com:1883
      topics:
        sessions: mqtt-sessions
        messages: mqtt-messages
        retained: mqtt-retained
      clients:
        - place/{identity}/#
    routes:
      - when:
          - publish:
              - topic: place/+/device/#
          - subscribe:
              - topic: place/+/device/#
        with:
          messages: mqtt-devices
        exit: kafka_cache_client
    exit: kafka_cache_client
