name: Release Cookbook Artifacts

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Tar all cookbooks
        run: for i in src/cookbooks/*/; do tar -zcvf "${i%/}.tar.gz" "$i"; done

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            src/cookbooks/*.tar.gz
            LICENSE
